# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ebdacbf53f2f7d55bea1c091a2619d19a370bc94d566c8bece1c1c55c768f793ec1e72043a3fa74514b31ce4ae67d445aa5d017ca7fc3db9f22602392c149ac

test:
  secret_key_base: a24f426e208b256302ea951d47d9cad24af961374c9a0b91e46e372f914c6722b28389b8ca81fd27059cae1a64a76abe1638f368ba06fd95f2f717bb14cee067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
