# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc72f07692faf70f6da2f858ec771dd3bafa1d449d36d4ffdcf8c1974e08d60b5e80724fcd8c47b73445df1025baba5328d07867d84edf6a1c3125f3957672c8

test:
  secret_key_base: 251d5119dea39a7d02671e7d63b2abf25416bfb0e64a3d82e6a6858cd600350efce24eae625144ac3d6c720fae43937a48192797bdace39aa1d997a8390144e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
